'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alertas_limites
    Public Property Tipo_Alerta As String
    Public Property month As Integer
    Public Property min As Nullable(Of Decimal)
    Public Property max As Nullable(Of Decimal)

End Class
