'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer_MDMMMA
    Public Property CustomerCode As String
    Public Property CustomerCodeMD As String
    Public Property MD As String
    Public Property CustomerCodeMM As String
    Public Property MM As String
    Public Property CustomerCodeMA As String
    Public Property MA As String
    Public Property CustomerName As String
    Public Property CustomerMarket As String

End Class
