'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Forecast_Product
    Public Property GenerationDate As Date
    Public Property Brand As String
    Public Property ProductCode As String
    Public Property VintageYear As String
    Public Property Package As String
    Public Property COREorMTF As Nullable(Of Boolean)
    Public Property InHand As Nullable(Of Double)
    Public Property ShipHand As Nullable(Of Double)
    Public Property SalesLY As Nullable(Of Double)
    Public Property MAT As Nullable(Of Double)
    Public Property Target As Nullable(Of Double)
    Public Property Target9L As Nullable(Of Double)
    Public Property AutomaticForecast As Nullable(Of Double)
    Public Property AdjustedForecast As Nullable(Of Double)
    Public Property FinalForecast As Nullable(Of Double)
    Public Property AvailableAllocation As Integer
    Public Property ForecastAccomplishment As Double
    Public Property MATvsFinalForecast As Double
    Public Property Notes As String
    Public Property ForecastJan As Nullable(Of Double)
    Public Property ForecastFeb As Nullable(Of Double)
    Public Property ForecastMar As Nullable(Of Double)
    Public Property ForecastApr As Nullable(Of Double)
    Public Property ForecastMay As Nullable(Of Double)
    Public Property ForecastJun As Nullable(Of Double)
    Public Property ForecastJul As Nullable(Of Double)
    Public Property ForecastAug As Nullable(Of Double)
    Public Property ForecastSep As Nullable(Of Double)
    Public Property ForecastOct As Nullable(Of Double)
    Public Property ForecastNov As Nullable(Of Double)
    Public Property ForecastDec As Nullable(Of Double)
    Public Property Warning As Nullable(Of Boolean)

End Class
