'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Forecast
    Public Property GenerationDate As Date
    Public Property ForecastMarket As String
    Public Property CustomerType As Nullable(Of Boolean)
    Public Property InvoiceCustomerCode As String
    Public Property InvoiceCustomer As String
    Public Property ForecastCustomerCode As String
    Public Property ForecastCustomer As String
    Public Property Brand As String
    Public Property ProductCode As String
    Public Property VintageYear As String
    Public Property Package As String
    Public Property PriceList As String
    Public Property Currency As String
    Public Property COREorMTF As Nullable(Of Boolean)
    Public Property InHand As Nullable(Of Double)
    Public Property ShipHand As Nullable(Of Double)
    Public Property SalesLY As Nullable(Of Double)
    Public Property MAT As Nullable(Of Double)
    Public Property Target As Nullable(Of Double)
    Public Property AutomaticForecast As Nullable(Of Double)
    Public Property AdjustedForecast As Nullable(Of Double)
    Public Property A_ As Nullable(Of Boolean)
    Public Property FinalForecast As Nullable(Of Double)
    Public Property AvailableAllocation As Nullable(Of Double)
    Public Property MOQ As Nullable(Of Double)
    Public Property ForecastAccomplishment As Nullable(Of Double)
    Public Property MATvsFinalForecast As Nullable(Of Double)
    Public Property WarningProductCustomer As Short
    Public Property Notes As String
    Public Property AjustJan As Nullable(Of Double)
    Public Property AjustFeb As Nullable(Of Double)
    Public Property AjustMar As Nullable(Of Double)
    Public Property AjustApr As Nullable(Of Double)
    Public Property AjustMay As Nullable(Of Double)
    Public Property AjustJun As Nullable(Of Double)
    Public Property AjustJul As Nullable(Of Double)
    Public Property AjustAug As Nullable(Of Double)
    Public Property AjustSep As Nullable(Of Double)
    Public Property AjustOct As Nullable(Of Double)
    Public Property AjustNov As Nullable(Of Double)
    Public Property AjustDec As Nullable(Of Double)
    Public Property ForecastJan As Nullable(Of Double)
    Public Property ForecastFeb As Nullable(Of Double)
    Public Property ForecastMar As Nullable(Of Double)
    Public Property ForecastApr As Nullable(Of Double)
    Public Property ForecastMay As Nullable(Of Double)
    Public Property ForecastJun As Nullable(Of Double)
    Public Property ForecastJul As Nullable(Of Double)
    Public Property ForecastAug As Nullable(Of Double)
    Public Property ForecastSep As Nullable(Of Double)
    Public Property ForecastOct As Nullable(Of Double)
    Public Property ForecastNov As Nullable(Of Double)
    Public Property ForecastDec As Nullable(Of Double)
    Public Property WeightsJan As Nullable(Of Double)
    Public Property WeightsFeb As Nullable(Of Double)
    Public Property WeightsMar As Nullable(Of Double)
    Public Property WeightsApr As Nullable(Of Double)
    Public Property WeightsMay As Nullable(Of Double)
    Public Property WeightsJun As Nullable(Of Double)
    Public Property WeightsJul As Nullable(Of Double)
    Public Property WeightsAug As Nullable(Of Double)
    Public Property WeightsSep As Nullable(Of Double)
    Public Property WeightsOct As Nullable(Of Double)
    Public Property WeightsNov As Nullable(Of Double)
    Public Property WeightsDec As Nullable(Of Double)
    Public Property Target9L As Nullable(Of Double)
    Public Property ProductName As String
    Public Property PackageCapacity As Nullable(Of Decimal)
    Public Property FinalForecast9L As Nullable(Of Double)
    Public Property WarningAllocation As Nullable(Of Boolean)
    Public Property FAmin As Nullable(Of Double)
    Public Property FAmax As Nullable(Of Double)
    Public Property MATFORmin As Nullable(Of Double)
    Public Property MATFORmax As Nullable(Of Double)
    Public Property timestamp As Nullable(Of Date)

End Class
