'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SalesSystemEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SalesSystemEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property SapClients() As DbSet(Of SapClients)
    Public Property SapForecast() As DbSet(Of SapForecast)
    Public Property SapMateriais() As DbSet(Of SapMateriais)
    Public Property SapClientsMDMMMA() As DbSet(Of SapClientsMDMMMA)
    Public Property SapMateriaisEmbalagem() As DbSet(Of SapMateriaisEmbalagem)
    Public Property SapImmaterialSales() As DbSet(Of SapImmaterialSales)
    Public Property queryForecastCliStatwithExceptions() As DbSet(Of queryForecastCliStatwithExceptions)

End Class
