'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class queryForecastCliStatwithExceptions
    Public Property CodCliFact As String
    Public Property CodCliDest As String
    Public Property Codigo As String
    Public Property TPRE As String
    Public Property Currency As String
    Public Property Year As Integer
    Public Property Period As Integer
    Public Property CliStatOrig As String
    Public Property EXTWG As String
    Public Property CliStatExcep As String
    Public Property Clistat As String

End Class
