'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SapClientsMDMMMA
    Public Property KUNNR As String
    Public Property MD As String
    Public Property MM As String
    Public Property MA As String
    Public Property KUNNRMD As String
    Public Property KUNNRMM As String
    Public Property KUNNRMA As String

End Class
