'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SapClients
    Public Property KUNNR As String
    Public Property NAME1 As String
    Public Property LAND1 As String
    Public Property LANDX50 As String
    Public Property WAERS As String
    Public Property MARKETDIRECTOR As String
    Public Property MARKETMANAGER As String
    Public Property MARKETASSISTANT As String
    Public Property CLIENTSTAT As String
    Public Property KATR3 As String
    Public Property KLIMK As Nullable(Of Decimal)
    Public Property DATADEALTERACAO As String
    Public Property KTOKD As String
    Public Property BRSCH As String
    Public Property CONTACTNAME As String
    Public Property CONTACTTELEPHONE As String
    Public Property CONTACTEMAIL As String
    Public Property ZZDIASTOLER As String
    Public Property ZTERMTEXT As String
    Public Property ZINCOTERMS As String
    Public Property ADVERTENCIA As String
    Public Property KATR4 As String

End Class
