'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SapForecast
    Public Property CodCliFact As String
    Public Property CodCliDest As String
    Public Property Codigo As String
    Public Property TPRE As String
    Public Property Currency As String
    Public Property Year As Integer
    Public Property Period As Integer
    Public Property Month1Value As Decimal
    Public Property Month2Value As Decimal
    Public Property Month3Value As Decimal
    Public Property Month4Value As Decimal
    Public Property Month5Value As Decimal
    Public Property Month6Value As Decimal
    Public Property Month7Value As Decimal
    Public Property Month8Value As Decimal
    Public Property Month9Value As Decimal
    Public Property Month10Value As Decimal
    Public Property Month11Value As Decimal
    Public Property Month12Value As Decimal
    Public Property AnualValue As Decimal
    Public Property UserCS As String
    Public Property timestamp As Nullable(Of Date)

End Class
