'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SapImmaterialSales
    Public Property Year As String
    Public Property InvClientID As String
    Public Property FinalClientID As String
    Public Property StatsClientId As String
    Public Property Material_Number As String
    Public Property MAKTX As String
    Public Property Immaterial_Number As String
    Public Property Price_List As String
    Public Property Currency As String
    Public Property ShipHand As Nullable(Of Decimal)
    Public Property ShipHandUnit As Nullable(Of Decimal)

End Class
