'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SapMateriais
    Public Property MATNR As String
    Public Property MAKTX As String
    Public Property WGBEZ60 As String
    Public Property EWBEZ As String
    Public Property NIV1ID As String
    Public Property NIV1 As String
    Public Property NIV2ID As String
    Public Property NIV2 As String
    Public Property NIV3ID As String
    Public Property NIV3 As String
    Public Property CATEGORIAID As String
    Public Property CATEGORIA As String
    Public Property SUBCATEGORIAID As String
    Public Property SUBCATEGORIA As String
    Public Property VINTAGEYEAR As String
    Public Property EMBALAGEM As String
    Public Property CHANGENR As String
    Public Property DATADEALTERACAO As String
    Public Property MEINS As String
    Public Property RANGE As String
    Public Property PMATN As String
    Public Property TIPO As String
    Public Property FAMILIA As String
    Public Property ZZORDLSTPRECO As String
    Public Property ZZGROUP As String
    Public Property GRUPO As String

End Class
